// Products
const PRODUCTS_FETCH = "PRODUCTS_FETCH";
const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
const PRODUCTS_FETCH_FAIL = "PRODUCTS_FETCH_FAIL";
const SORT_BY_PRICE_ASC = "SORT_BY_PRICE_ASC";
const SORT_BY_PRICE_DESC = "SORT_BY_PRICE_DESC";
const SORT_BY_DATE_ASC = "SORT_BY_DATE_ASC";
const SORT_BY_DATE_DESC = "SORT_BY_DATE_DESC";

// Companies
const COMPANIES_FETCH = "COMPANIES_FETCH";
const COMPANIES_FETCH_SUCCESS = "COMPANIES_FETCH_SUCCESS";
const COMPANIES_FETCH_FAIL = "COMPANIES_FETCH_FAIL";

// Tags
const TAGS_FETCH = "TAGS_FETCH";
const TAGS_FETCH_SUCCESS = "TAGS_FETCH_SUCCESS";
const TAGS_FETCH_FAIL = "TAGS_FETCH_FAIL";

// Cart
const CART_ADD_ITEM = "CART_ADD_ITEM";
const CART_INCREASE_QTY = "CART_INCREASE_QTY";
const CART_DECREASE_QTY = "CART_DECREASE_QTY";
const CART_SET_SPINNER = "CART_SET_SPINNER";
const CART_UNSET_SPINNER = "CART_UNSET_SPINNER";
const CART_TOTAL = "CART_TOTAL";

// Common
const SET_MODAL_OPEN = "SET_MODAL_OPEN";
const SET_MODAL_CLOSE = "SET_MODAL_CLOSE";

export {
  PRODUCTS_FETCH,
  PRODUCTS_FETCH_SUCCESS,
  PRODUCTS_FETCH_FAIL,
  SORT_BY_PRICE_ASC,
  SORT_BY_PRICE_DESC,
  SORT_BY_DATE_ASC,
  SORT_BY_DATE_DESC,
  COMPANIES_FETCH,
  COMPANIES_FETCH_SUCCESS,
  COMPANIES_FETCH_FAIL,
  TAGS_FETCH,
  TAGS_FETCH_SUCCESS,
  TAGS_FETCH_FAIL,
  CART_ADD_ITEM,
  CART_INCREASE_QTY,
  CART_DECREASE_QTY,
  CART_TOTAL,
  CART_SET_SPINNER,
  CART_UNSET_SPINNER,
  SET_MODAL_OPEN,
  SET_MODAL_CLOSE,
};
