// Products
const PRODUCTS_FETCH = "PRODUCTS_FETCH";
const PRODUCTS_FETCH_SUCCESS = "PRODUCTS_FETCH_SUCCESS";
const PRODUCTS_FETCH_FAIL = "PRODUCTS_FETCH_FAIL";
const FILTER_PRODUCTS_BY_BRAND = "FILTER_PRODUCTS_BY_BRAND";
const FILTER_PRODUCTS_BY_TAG = "FILTER_PRODUCTS_BY_TAG";
const SORT_PRODUCTS = "SORT_PRODUCTS";

// Companies
const COMPANIES_FETCH = "COMPANIES_FETCH";
const COMPANIES_FETCH_SUCCESS = "COMPANIES_FETCH_SUCCESS";
const COMPANIES_FETCH_FAIL = "COMPANIES_FETCH_FAIL";

// Tags
const TAGS_FETCH = "TAGS_FETCH";
const TAGS_FETCH_SUCCESS = "TAGS_FETCH_SUCCESS";
const TAGS_FETCH_FAIL = "TAGS_FETCH_FAIL";

// Cart
const CART_ADD_ITEM = "CART_ADD_ITEM";
const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
const CART_UPDATE_ITEM = "CART_UPDATE_ITEM";

// Errors
const INSERT_ERROR = "INSERT_ERROR";
const CLEAR_ERROR = "CLEAR_ERROR";

export {
  PRODUCTS_FETCH,
  PRODUCTS_FETCH_SUCCESS,
  PRODUCTS_FETCH_FAIL,
  FILTER_PRODUCTS_BY_BRAND,
  FILTER_PRODUCTS_BY_TAG,
  SORT_PRODUCTS,
  COMPANIES_FETCH,
  COMPANIES_FETCH_SUCCESS,
  COMPANIES_FETCH_FAIL,
  TAGS_FETCH,
  TAGS_FETCH_SUCCESS,
  TAGS_FETCH_FAIL,
  CART_ADD_ITEM,
  CART_REMOVE_ITEM,
  CART_UPDATE_ITEM,
  INSERT_ERROR,
  CLEAR_ERROR,
};
